// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kafkaStreamsExample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class SensorDataTransformed : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SensorDataTransformed\",\"namespace\":\"com.kafkaStreamsExam" +
				"ple\",\"fields\":[{\"name\":\"sensorId\",\"type\":\"string\"},{\"name\":\"check\",\"type\":{\"type" +
				"\":\"map\",\"values\":\"string\"}},{\"name\":\"timestamp\",\"type\":[\"string\",\"null\"]}]}");
		private string _sensorId;
		private IDictionary<string,System.String> _check;
		private string _timestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SensorDataTransformed._SCHEMA;
			}
		}
		public string sensorId
		{
			get
			{
				return this._sensorId;
			}
			set
			{
				this._sensorId = value;
			}
		}
		public IDictionary<string,System.String> check
		{
			get
			{
				return this._check;
			}
			set
			{
				this._check = value;
			}
		}
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sensorId;
			case 1: return this.check;
			case 2: return this.timestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sensorId = (System.String)fieldValue; break;
			case 1: this.check = (IDictionary<string,System.String>)fieldValue; break;
			case 2: this.timestamp = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
