// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kafkaStreamsExample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class SensorData : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""SensorData"",""namespace"":""com.kafkaStreamsExample"",""fields"":[{""name"":""sensorId"",""type"":""string""},{""name"":""value"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""value_record"",""namespace"":""com.kafkaStreamsExample"",""fields"":[{""name"":""type"",""type"":""string""},{""name"":""value"",""type"":""double""},{""name"":""unit"",""type"":""string""}]}}},{""name"":""timestamp"",""type"":[""string"",""null""]}]}");
		private string _sensorId;
		private IList<com.kafkaStreamsExample.value_record> _value;
		private string _timestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SensorData._SCHEMA;
			}
		}
		public string sensorId
		{
			get
			{
				return this._sensorId;
			}
			set
			{
				this._sensorId = value;
			}
		}
		public IList<com.kafkaStreamsExample.value_record> value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sensorId;
			case 1: return this.value;
			case 2: return this.timestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sensorId = (System.String)fieldValue; break;
			case 1: this.value = (IList<com.kafkaStreamsExample.value_record>)fieldValue; break;
			case 2: this.timestamp = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
