// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kafkaStreamsExample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class SensorDataAggregation : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SensorDataAggregation\",\"namespace\":\"com.kafkaStreamsExam" +
				"ple\",\"fields\":[{\"name\":\"valueAvg\",\"type\":\"double\"},{\"name\":\"count\",\"type\":\"int\"}" +
				",{\"name\":\"unit\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}]}");
		private double _valueAvg;
		private int _count;
		private string _unit;
		private string _timestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SensorDataAggregation._SCHEMA;
			}
		}
		public double valueAvg
		{
			get
			{
				return this._valueAvg;
			}
			set
			{
				this._valueAvg = value;
			}
		}
		public int count
		{
			get
			{
				return this._count;
			}
			set
			{
				this._count = value;
			}
		}
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				this._unit = value;
			}
		}
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.valueAvg;
			case 1: return this.count;
			case 2: return this.unit;
			case 3: return this.timestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.valueAvg = (System.Double)fieldValue; break;
			case 1: this.count = (System.Int32)fieldValue; break;
			case 2: this.unit = (System.String)fieldValue; break;
			case 3: this.timestamp = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
