// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kafkaStreamsExample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class value_record : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"value_record\",\"namespace\":\"com.kafkaStreamsExample\",\"fie" +
				"lds\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"double\"},{\"name\":\"" +
				"unit\",\"type\":\"string\"}]}");
		private string _type;
		private double _value;
		private string _unit;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return value_record._SCHEMA;
			}
		}
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		public double value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				this._unit = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.type;
			case 1: return this.value;
			case 2: return this.unit;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.type = (System.String)fieldValue; break;
			case 1: this.value = (System.Double)fieldValue; break;
			case 2: this.unit = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
